name: Test

on: [push, pull_request]

jobs:
  test:
    name: RSpec
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.2', '3.2' ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rake spec
